# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      # Deploy dist to the server
      - name: Deploy to remote server
        run: scp -r -P 18765 ./dist/* u2433-a9rqywtd0bh4@gnldm1064.siteground.biz:www/nikola-nenovski.info/public_html
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Show deployment link
        run: echo "Deployed! https://nikola-nenovski.info"
